import { DEFAULT_FILAMENT, makeFilament, type FilamentProfile } from '../../models/filament.model';
import {
  DEFAULT_PRINT_PROFILE,
  makePrintProfile,
  type PrintProfile,
} from '../../models/print-profile.model';
import { DEFAULT_PRINTER, makePrinter, type PrinterProfile } from '../../models/printer.model';

/**
 * Bundled read-only vendor dataset that stands in for the cloud catalog.
 *
 * These entries are the "base data" other slicers ship with (Orca / Prusa /
 * Bambu). Here they live behind the {@link CloudCatalog} abstraction so an
 * offline install ships with exactly ONE default per category (see
 * `DEFAULT_*`) and gains the variety only when the cloud is reachable. Nothing
 * here is ever written to local storage as-is — importing produces a `user`
 * copy (see {@link CloudCatalog.importCopy}).
 *
 * The single offline defaults are intentionally excluded from the catalog so
 * they are never listed twice.
 */

export const CATALOG_PRINTERS: PrinterProfile[] = [
  makePrinter({
    id: 'cat-prusa-mk4',
    name: 'Prusa MK4',
    source: 'catalog',
    vendor: 'Prusa Research',
    model: 'MK4',
    bedWidth: 250,
    bedDepth: 210,
    bedHeight: 220,
    nozzleDiameter: 0.4,
    maxPrintSpeed: 200,
    maxTravelSpeed: 300,
    retractionLength: 0.7,
    gcodeFlavor: 'marlin',
  }),
  makePrinter({
    id: 'cat-prusa-mini',
    name: 'Prusa MINI+',
    source: 'catalog',
    vendor: 'Prusa Research',
    model: 'MINI+',
    bedWidth: 180,
    bedDepth: 180,
    bedHeight: 180,
    nozzleDiameter: 0.4,
    maxPrintSpeed: 150,
  }),
  makePrinter({
    id: 'cat-bambu-x1c',
    name: 'Bambu Lab X1 Carbon',
    source: 'catalog',
    vendor: 'Bambu Lab',
    model: 'X1C',
    bedWidth: 256,
    bedDepth: 256,
    bedHeight: 256,
    nozzleDiameter: 0.4,
    maxPrintSpeed: 500,
    maxTravelSpeed: 500,
    retractionLength: 0.8,
    gcodeFlavor: 'marlin',
    connection: { kind: 'bambu', connected: false },
  }),
  makePrinter({
    id: 'cat-bambu-a1',
    name: 'Bambu Lab A1',
    source: 'catalog',
    vendor: 'Bambu Lab',
    model: 'A1',
    bedWidth: 256,
    bedDepth: 256,
    bedHeight: 256,
    maxPrintSpeed: 500,
    connection: { kind: 'bambu', connected: false },
  }),
  makePrinter({
    id: 'cat-ender3-v3',
    name: 'Creality Ender-3 V3',
    source: 'catalog',
    vendor: 'Creality',
    model: 'Ender-3 V3',
    bedWidth: 220,
    bedDepth: 220,
    bedHeight: 250,
    maxPrintSpeed: 250,
    gcodeFlavor: 'klipper',
  }),
  makePrinter({
    id: 'cat-voron-24-350',
    name: 'Voron 2.4 (350)',
    source: 'catalog',
    vendor: 'Voron Design',
    model: '2.4 R2 350',
    bedWidth: 350,
    bedDepth: 350,
    bedHeight: 340,
    maxPrintSpeed: 300,
    maxTravelSpeed: 400,
    gcodeFlavor: 'klipper',
    connection: { kind: 'moonraker', connected: false },
  }),
  makePrinter({
    id: 'cat-anycubic-kobra2',
    name: 'Anycubic Kobra 2',
    source: 'catalog',
    vendor: 'Anycubic',
    model: 'Kobra 2',
    bedWidth: 220,
    bedDepth: 220,
    bedHeight: 250,
    maxPrintSpeed: 250,
  }),
];

export const CATALOG_FILAMENTS: FilamentProfile[] = [
  makeFilament({
    id: 'cat-prusament-pla-galaxy-black',
    name: 'Prusament PLA Galaxy Black',
    source: 'catalog',
    vendor: 'Prusament',
    material: 'PLA',
    color: '#1c1c22',
    nozzleTemp: 215,
    costPerKg: 30,
  }),
  makeFilament({
    id: 'cat-prusament-petg-orange',
    name: 'Prusament PETG Orange',
    source: 'catalog',
    vendor: 'Prusament',
    material: 'PETG',
    color: '#e0730f',
    costPerKg: 30,
  }),
  makeFilament({
    id: 'cat-bambu-pla-basic-white',
    name: 'Bambu PLA Basic White',
    source: 'catalog',
    vendor: 'Bambu Lab',
    material: 'PLA',
    color: '#f4f4f6',
    maxVolumetricSpeed: 21,
    costPerKg: 25,
  }),
  makeFilament({
    id: 'cat-overture-petg-black',
    name: 'Overture PETG Black',
    source: 'catalog',
    vendor: 'Overture',
    material: 'PETG',
    color: '#141418',
    costPerKg: 20,
  }),
  makeFilament({
    id: 'cat-polymaker-asa-grey',
    name: 'Polymaker ASA Grey',
    source: 'catalog',
    vendor: 'Polymaker',
    material: 'ASA',
    color: '#8a8a90',
    costPerKg: 28,
  }),
  makeFilament({
    id: 'cat-hatchbox-abs-red',
    name: 'Hatchbox ABS Red',
    source: 'catalog',
    vendor: 'Hatchbox',
    material: 'ABS',
    color: '#b02020',
    costPerKg: 22,
  }),
  makeFilament({
    id: 'cat-sunlu-plaplus-grey',
    name: 'SUNLU PLA+ Grey',
    source: 'catalog',
    vendor: 'SUNLU',
    material: 'PLA',
    color: '#6a6a70',
    nozzleTemp: 210,
    costPerKg: 18,
  }),
  makeFilament({
    id: 'cat-ninjaflex-tpu-blue',
    name: 'NinjaFlex TPU Blue',
    source: 'catalog',
    vendor: 'NinjaTek',
    material: 'TPU',
    color: '#2060c0',
    costPerKg: 60,
  }),
  makeFilament({
    id: 'cat-generic-pva-support',
    name: 'Generic PVA Support',
    source: 'catalog',
    vendor: 'Generic',
    material: 'PVA',
    color: '#e8e0c8',
    costPerKg: 70,
  }),
];

export const CATALOG_PROFILES: PrintProfile[] = [
  makePrintProfile({
    id: 'cat-draft-028',
    name: 'Draft — 0.28 mm',
    source: 'catalog',
    quality: 'draft',
    layerHeight: 0.28,
    firstLayerHeight: 0.3,
    wallCount: 2,
    topLayers: 3,
    bottomLayers: 3,
    infillDensity: 0.15,
  }),
  makePrintProfile({
    id: 'cat-optimal-016',
    name: 'Optimal — 0.16 mm',
    source: 'catalog',
    quality: 'standard',
    layerHeight: 0.16,
    firstLayerHeight: 0.2,
    wallCount: 3,
    topLayers: 5,
    bottomLayers: 4,
    infillDensity: 0.2,
  }),
  makePrintProfile({
    id: 'cat-fine-012',
    name: 'Fine — 0.12 mm',
    source: 'catalog',
    quality: 'fine',
    layerHeight: 0.12,
    firstLayerHeight: 0.16,
    wallCount: 4,
    topLayers: 6,
    bottomLayers: 5,
    infillDensity: 0.25,
    speedPrint: 90,
  }),
  makePrintProfile({
    id: 'cat-ultra-008',
    name: 'Ultra fine — 0.08 mm',
    source: 'catalog',
    quality: 'fine',
    layerHeight: 0.08,
    firstLayerHeight: 0.12,
    wallCount: 4,
    topLayers: 8,
    bottomLayers: 6,
    infillDensity: 0.25,
    speedPrint: 70,
    ironingEnabled: true,
  }),
  makePrintProfile({
    id: 'cat-strong-020',
    name: 'Strong — 0.20 mm',
    source: 'catalog',
    quality: 'standard',
    layerHeight: 0.2,
    wallCount: 5,
    topLayers: 6,
    bottomLayers: 5,
    infillDensity: 0.4,
    infillPattern: 'Honeycomb',
  }),
  makePrintProfile({
    id: 'cat-fast-024',
    name: 'Fast draft — 0.24 mm',
    source: 'catalog',
    quality: 'draft',
    layerHeight: 0.24,
    wallCount: 2,
    topLayers: 3,
    bottomLayers: 3,
    infillDensity: 0.1,
    infillPattern: 'Rectilinear',
    speedPrint: 200,
    speedInfill: 250,
  }),
];

/** The offline defaults, excluded from the catalog so they are never listed twice. */
export const OFFLINE_DEFAULT_IDS = new Set<string>([
  DEFAULT_PRINTER.id,
  DEFAULT_FILAMENT.id,
  DEFAULT_PRINT_PROFILE.id,
]);
