//! Slicing the same model twice must produce the same G-code.
//!
//! This is not a quality metric — it is the precondition for every other one.
//! A QA baseline, a before/after render and a bisect all assume the slicer is a
//! function of its input, and for a long time it was not: the Arachne
//! generator's Voronoi beach line drew its shape from an OS-seeded generator
//! (see `vendor/cpp_map/PATCH.md`), and the surface trim unioned its bead
//! buckets in `HashMap` order. The same Benchy sliced twice came out different
//! both within one process and between two.

#[path = "qa/mod.rs"]
mod qa;

use slicer_engine::settings::params::WallGenerator;
use std::path::Path;

/// Everything about a layer that reaches the G-code: geometry, role, both width
/// forms, and whether the path is open. An earlier version of this digest left
/// the per-vertex widths out and reported a stable slice that was not one.
fn digest(layers: &[slicer_engine::core::SliceLayer]) -> String {
    let mut h: u64 = 1469598103934665603;
    let mut feed = |bytes: &[u8]| {
        for b in bytes {
            h ^= *b as u64;
            h = h.wrapping_mul(1099511628211);
        }
    };
    for l in layers {
        feed(format!("z{:.6}", l.z).as_bytes());
        for (i, p) in l.paths.iter().enumerate() {
            feed(format!("{:?}", l.path_roles.get(i)).as_bytes());
            feed(format!("{:?}", l.path_widths.get(i)).as_bytes());
            feed(format!("{:?}", l.path_vertex_widths.get(i)).as_bytes());
            feed(format!("{}", l.is_path_open(i)).as_bytes());
            for q in p.iter() {
                feed(format!("{:.6},{:.6}", q.x(), q.y()).as_bytes());
            }
        }
    }
    format!("{h:016x}")
}

/// Both generators, three slices each, one answer.
///
/// Three rather than two because the failure this guards against was not a
/// clean two-way split: twenty Voronoi builds of one region once returned five
/// different diagrams, so a two-run check would have passed by luck often
/// enough to be useless.
#[test]
fn slicing_the_same_model_twice_gives_the_same_gcode() {
    let mesh = qa::prepare(Path::new("3DBenchy.stl")).expect("prepare benchy");

    for g in [WallGenerator::Arachne, WallGenerator::Classic] {
        let params = slicer_engine::settings::params::SlicingParams {
            wall_generator: g,
            layer_height: 0.2,
            ..Default::default()
        };
        let mut layer_digests = Vec::new();
        let mut gcode = Vec::new();
        for _ in 0..3 {
            // One slice per round, with the G-code derived from those same
            // layers — so a failure says which of the two stages moved.
            let layers = slicer_engine::core::process_mesh(
                &mesh,
                &params,
                &slicer_engine::logging::NullLogger,
            );
            layer_digests.push(digest(&layers));
            gcode.push(
                slicer_engine::gcode::GcodeGenerator::new(
                    slicer_engine::gcode::GcodeFlavor::Marlin,
                )
                .generate(&layers, &params),
            );
        }

        assert!(
            layer_digests.iter().all(|d| d == &layer_digests[0]),
            "{g:?}: three slices of one mesh produced different geometry: {layer_digests:?}"
        );
        // Everything but the `; generated by … on <date> at <time>` line, which
        // is a clock reading rather than a slicing result and changes whenever
        // two slices straddle a second.
        let body = |s: &String| -> String {
            s.lines()
                .filter(|l| !l.starts_with("; generated by"))
                .collect::<Vec<_>>()
                .join("\n")
        };
        let bodies: Vec<String> = gcode.iter().map(body).collect();
        assert!(
            bodies.iter().all(|s| s == &bodies[0]),
            "{g:?}: three slices of one mesh produced different G-code"
        );
    }
}
