//! The G-code move IR.
//!
//! Emission used to append strings directly, so the program never existed as
//! *moves* and a plugin could only have edited finished text. Post-processing
//! text is explicitly not how this engine extends — it sees no geometry, no
//! roles, no settings — which is why native arc welding had nothing to attach
//! to. These tests pin that there is now a point at which the program is
//! structured, that a filter can rewrite it, and that having no filter changes
//! nothing.

use slicer_engine::core::{process_mesh, ExtrusionRole};
use slicer_engine::gcode::{GcodeFlavor, GcodeGenerator, Move, MoveFilter, MoveProgram};
use slicer_engine::logging::NullLogger;
use slicer_engine::mesh::types::Mesh;
use slicer_engine::plugin::{Plugin, PluginManifest};
use slicer_engine::settings::params::SlicingParams;
use std::sync::atomic::{AtomicUsize, Ordering};

fn fixture() -> Mesh {
    let path = std::path::Path::new(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/Voron_Design_Cube_v7.stl"
    ));
    slicer_engine::mesh::io::read_mesh(path).expect("fixture mesh")
}

#[test]
fn a_generator_with_no_filters_renders_what_it_planned() {
    // The property the whole split rests on: introducing the IR must not
    // change a single byte for anyone not using it.
    let mesh = fixture();
    let p = SlicingParams::default();
    let layers = process_mesh(&mesh, &p, &NullLogger);

    // Minus the header's wall-clock stamp, which is the one line that is not a
    // function of the input.
    let render = |g: GcodeGenerator| -> String {
        g.generate(&layers, &p)
            .lines()
            .filter(|l| !l.starts_with("; generated by "))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let plain = render(GcodeGenerator::new(GcodeFlavor::Marlin));
    let filtered = render(GcodeGenerator::new(GcodeFlavor::Marlin).with_move_filters(Vec::new()));
    assert_eq!(plain, filtered);
}

static SEEN_EXTRUDES: AtomicUsize = AtomicUsize::new(0);
static SEEN_TRAVELS: AtomicUsize = AtomicUsize::new(0);

/// A filter that only looks — enough to prove motion reaches a filter as
/// structure rather than text.
struct Observe;

impl MoveFilter for Observe {
    fn name(&self) -> &str {
        "observe"
    }
    fn filter(&self, program: &mut MoveProgram, _params: &SlicingParams) {
        for m in program.moves() {
            match m {
                Move::Extrude { .. } => {
                    SEEN_EXTRUDES.fetch_add(1, Ordering::SeqCst);
                }
                Move::Travel { .. } => {
                    SEEN_TRAVELS.fetch_add(1, Ordering::SeqCst);
                }
                _ => {}
            }
        }
    }
}

#[test]
fn motion_reaches_a_filter_as_structure() {
    let mesh = fixture();
    let p = SlicingParams::default();
    let layers = process_mesh(&mesh, &p, &NullLogger);

    SEEN_EXTRUDES.store(0, Ordering::SeqCst);
    SEEN_TRAVELS.store(0, Ordering::SeqCst);
    let _ = GcodeGenerator::new(GcodeFlavor::Marlin)
        .with_move_filters(vec![Box::new(Observe)])
        .generate(&layers, &p);

    assert!(
        SEEN_EXTRUDES.load(Ordering::SeqCst) > 1000,
        "extrusions must arrive as Move::Extrude, not as text"
    );
    assert!(
        SEEN_TRAVELS.load(Ordering::SeqCst) > 10,
        "travels must arrive as Move::Travel"
    );
}

/// A filter that drops every travel comment — a rewrite that is visible in the
/// output and impossible to do without seeing the program as moves.
struct StripTravelComments;

impl MoveFilter for StripTravelComments {
    fn name(&self) -> &str {
        "strip-travel-comments"
    }
    fn filter(&self, program: &mut MoveProgram, _params: &SlicingParams) {
        for m in program.moves_mut() {
            if let Move::Travel { comment, .. } = m {
                *comment = None;
            }
        }
    }
}

#[test]
fn a_filter_rewrite_reaches_the_rendered_output() {
    let mesh = fixture();
    let p = SlicingParams::default();
    let layers = process_mesh(&mesh, &p, &NullLogger);

    let plain = GcodeGenerator::new(GcodeFlavor::Marlin).generate(&layers, &p);
    let stripped = GcodeGenerator::new(GcodeFlavor::Marlin)
        .with_move_filters(vec![Box::new(StripTravelComments)])
        .generate(&layers, &p);

    assert!(
        plain.contains("; travel"),
        "the baseline has travel comments"
    );
    assert!(
        !stripped
            .lines()
            .any(|l| l.starts_with("G1 ") && l.ends_with("; travel")),
        "the filter's rewrite must survive to the rendered text"
    );
}

/// A filter that merges runs of collinear extrusions — the shape an arc welder
/// takes, without the arcs.
struct MergeCollinear;

impl MoveFilter for MergeCollinear {
    fn name(&self) -> &str {
        "merge-collinear"
    }
    fn filter(&self, program: &mut MoveProgram, _params: &SlicingParams) {
        let source = std::mem::take(program.moves_mut());
        let mut out: Vec<Move> = Vec::with_capacity(source.len());

        for m in source {
            // Fold a horizontal extrusion into the one before it when they
            // share a role and feedrate and lie on the same line: consume a run
            // of moves and emit fewer, which is the shape an arc welder takes.
            let merged = match (out.last_mut(), &m) {
                (
                    Some(Move::Extrude {
                        x: px,
                        y: py,
                        z: None,
                        e: pe,
                        de: pde,
                        feed_mm_min: pf,
                        role: prole,
                        ..
                    }),
                    Move::Extrude {
                        x,
                        y,
                        z: None,
                        e,
                        de,
                        feed_mm_min,
                        role,
                        ..
                    },
                ) if role == prole
                    && (feed_mm_min - *pf).abs() < 1e-9
                    && (y - *py).abs() < 1e-9 =>
                {
                    *px = *x;
                    *pe = *e;
                    *pde += *de;
                    true
                }
                _ => false,
            };
            if !merged {
                out.push(m);
            }
        }

        *program.moves_mut() = out;
    }
}

#[test]
fn a_filter_can_merge_moves_the_way_an_arc_welder_would() {
    // Not arc welding, but the same shape of rewrite: consume a run of
    // extrusions and emit fewer. If the IR can express that, it can carry
    // #32's native welder.
    let mut program = MoveProgram::new();
    for k in 1..=4 {
        program.push(Move::Extrude {
            x: k as f64,
            y: 0.0,
            z: None,
            e: k as f64 * 0.1,
            de: 0.1,
            feed_mm_min: 1800.0,
            role: ExtrusionRole::OuterWall,
            width_mm: 0.4,
            comment: None,
        });
    }
    assert_eq!(program.len(), 4);

    MergeCollinear.filter(&mut program, &SlicingParams::default());

    assert_eq!(program.len(), 1, "a collinear run folds into one move");
    match &program.moves()[0] {
        Move::Extrude { x, de, .. } => {
            assert_eq!(*x, 4.0, "the merged move ends where the run ended");
            assert!(
                (de - 0.4).abs() < 1e-9,
                "and carries the run's whole extrusion ({de})"
            );
        }
        other => panic!("expected one extrusion, got {other:?}"),
    }
}

/// A plugin that contributes a filter, to prove the hook is wired.
struct Welder;

impl Plugin for Welder {
    fn manifest(&self) -> PluginManifest {
        PluginManifest::experiment("welder", "Welder", "Contributes a move filter.")
    }
    fn move_filter(&self) -> Option<Box<dyn MoveFilter>> {
        Some(Box::new(StripTravelComments))
    }
}

#[test]
fn a_plugin_contributes_its_filter_through_the_hook() {
    let plugins: Vec<Box<dyn Plugin>> = vec![Box::new(Welder)];
    let filters = slicer_engine::plugin::move_filters(&plugins);
    assert_eq!(filters.len(), 1);
    assert_eq!(filters[0].name(), "strip-travel-comments");
}

#[test]
fn the_default_plugin_contributes_no_filter() {
    struct Quiet;
    impl Plugin for Quiet {
        fn manifest(&self) -> PluginManifest {
            PluginManifest::experiment("quiet", "Quiet", "Does nothing.")
        }
    }
    let plugins: Vec<Box<dyn Plugin>> = vec![Box::new(Quiet)];
    assert!(slicer_engine::plugin::move_filters(&plugins).is_empty());
}
