//! The plugin hook contract.
//!
//! The design's non-negotiable constraint is that **with no plugin active the
//! output is byte-identical**. These tests pin that, and the two things that
//! would quietly falsify it: a stage list that has silently changed shape, and
//! an inserted stage that perturbs the pipeline merely by existing.
//!
//! ## Why the comparisons carry a tolerance
//!
//! "Byte-identical" is asserted against what the engine actually delivers, and
//! two slices of the same mesh in the same process are not quite bit-equal
//! **when other work is running alongside**. Sliced alone, six consecutive
//! slices of the fixture agree to the last digit on every role. Sliced while
//! the rest of this file's tests are running, `Gap infill` regroups — one run
//! emits two short beads where the next merges them into one — and `Sparse
//! infill` follows it by a hair, because the gap-fill footprint is subtracted
//! out of the infill boundary. AGENTS.md records the same symptom as a couple
//! of millimetres of `gap_fill` drift between Benchy slices.
//!
//! Measured here, the drift is **0.07 mm on a 46-metre role** — around one part
//! per million. It is pre-existing behaviour of the wall generator with nothing
//! to do with plugins, but it will happily masquerade as a plugin regression.
//!
//! So the comparisons use the same `abs`-or-`rel` shape the QA gate uses for
//! role lengths. Every steady role is held to **1 mm or 0.05 %**, against
//! measured noise of 0.07 mm; `Gap infill` — proportionally the noisiest, at
//! 1.2 mm on a 434 mm role — keeps the QA gate's own 5 %, for the reason that
//! gate states: the medial beads are float-sensitive. Both leave at least an
//! order of magnitude over the noise while staying far below anything real. A
//! stage that actually perturbed the pipeline moves a role by whole metres, and
//! a dropped or doubled feature is a 100 % swing.

use std::collections::BTreeMap;
use std::sync::atomic::{AtomicUsize, Ordering};

use slicer_engine::core::stages::{core_stages, ids};
use slicer_engine::core::{process_mesh, process_mesh_with_plugins, ExtrusionRole};
use slicer_engine::gcode::{GcodeFlavor, GcodeGenerator};
use slicer_engine::logging::NullLogger;
use slicer_engine::mesh::types::Mesh;
use slicer_engine::plugin::{
    FnStage, Plugin, PluginManifest, SliceContext, Stage, StageId, StageRegistration, StageWrapper,
};
use slicer_engine::settings::params::SlicingParams;

fn fixture() -> Mesh {
    let path = std::path::Path::new(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/Voron_Design_Cube_v7.stl"
    ));
    slicer_engine::mesh::io::read_mesh(path).expect("fixture mesh")
}

fn params() -> SlicingParams {
    SlicingParams::default()
}

/// Render `layers` to G-code, minus the one line that is a wall-clock stamp.
///
/// Everything else in the file is a function of the input, which is what these
/// tests are comparing; the `; generated by … at HH:MM:SS` line is not.
fn to_gcode(layers: &[slicer_engine::core::SliceLayer], p: &SlicingParams) -> String {
    GcodeGenerator::new(GcodeFlavor::Marlin)
        .generate(layers, p)
        .lines()
        .filter(|line| !line.starts_with("; generated by "))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Extruded millimetres per `;TYPE:` role, plus the layer count.
///
/// The comparable projection of a G-code file: it captures what each role
/// actually deposited and where, without being hostage to the accumulator
/// drift that a regrouped gap-fill bead causes downstream.
#[derive(Debug, Default, PartialEq)]
struct Deposited {
    layers: usize,
    per_role: BTreeMap<String, f64>,
}

fn deposited(gcode: &str) -> Deposited {
    let mut out = Deposited::default();
    let (mut x, mut y) = (0.0_f64, 0.0_f64);
    let mut role = String::new();

    for line in gcode.lines() {
        if let Some(name) = line.strip_prefix(";TYPE:") {
            role = name.trim().to_string();
            continue;
        }
        if line.starts_with(";LAYER_CHANGE") {
            out.layers += 1;
            continue;
        }
        if !(line.starts_with("G1 ") || line.starts_with("G0 ")) {
            continue;
        }
        let (mut nx, mut ny, mut e) = (None, None, None);
        for token in line.split_whitespace().skip(1) {
            let (tag, rest) = token.split_at(1);
            match tag {
                "X" => nx = rest.parse::<f64>().ok(),
                "Y" => ny = rest.parse::<f64>().ok(),
                "E" => e = rest.parse::<f64>().ok(),
                _ => {}
            }
        }
        let (nx, ny) = (nx.unwrap_or(x), ny.unwrap_or(y));
        // Absolute E, so a retract shows as a decrease; only forward motion
        // with the nozzle moving counts as deposited material.
        if e.is_some_and(|e| e > 0.0) {
            let d = ((nx - x).powi(2) + (ny - y).powi(2)).sqrt();
            if d > 0.0 {
                *out.per_role.entry(role.clone()).or_default() += d;
            }
        }
        x = nx;
        y = ny;
    }
    out
}

/// Tolerance for one role's deposited length: a match is within `ABS_MM` **or**
/// within the role's relative allowance, whichever is larger.
const ABS_MM: f64 = 1.0;

/// Relative allowance for every role the engine is steady about — 0.05 %, i.e.
/// two orders of magnitude above the drift measured on them (0.07 mm on a
/// 46-metre role) and orders of magnitude below a real perturbation.
const REL: f64 = 0.0005;

/// Gap fill gets the **QA gate's own** 5 %, for the reason that gate gives:
/// the medial beads are float-sensitive, and their grouping is what actually
/// moves between two runs. Measured drift here is 1.2 mm on a 434 mm role
/// (0.27 %), so this still leaves an order of magnitude of headroom — while a
/// stage that genuinely disturbed gap fill would swing it by far more.
const GAP_FILL_REL: f64 = 0.05;

/// The role whose beads regroup between runs — see the module comment.
const GAP_FILL: &str = "Gap infill";

/// Assert two slices deposited the same material in the same places.
///
/// The role set must match exactly — a stage that dropped or invented a whole
/// extrusion role is a categorical failure, not a numeric one — and every
/// role's length must agree within tolerance.
fn assert_same_deposition(baseline: &Deposited, other: &Deposited, what: &str) {
    assert_eq!(baseline.layers, other.layers, "{what}: layer count");
    assert_eq!(
        baseline.per_role.keys().collect::<Vec<_>>(),
        other.per_role.keys().collect::<Vec<_>>(),
        "{what}: the set of extrusion roles must be identical"
    );

    for (role, &base) in &baseline.per_role {
        let cur = other.per_role[role];
        let rel = if role == GAP_FILL { GAP_FILL_REL } else { REL };
        assert!(
            (cur - base).abs() <= ABS_MM.max(rel * base.abs()),
            "{what}: role '{role}' deposited {cur:.4} mm against {base:.4} mm — \
             beyond the {ABS_MM} mm / {pct}% tolerance",
            pct = rel * 100.0
        );
    }
}

// ── The byte-identity constraint ────────────────────────────────────────────

/// A plugin that registers a stage doing nothing at all.
struct NoOp;

impl Plugin for NoOp {
    fn manifest(&self) -> PluginManifest {
        PluginManifest::experiment("no-op", "No-op", "Registers a stage that does nothing.")
    }
    fn stages(&self) -> Vec<StageRegistration> {
        vec![
            StageRegistration::before(ids::SLICING, FnStage::boxed("no-op:first", |_| {})),
            StageRegistration::after(ids::INFILL, FnStage::boxed("no-op:mid", |_| {})),
            StageRegistration::after(
                ids::FIRST_LAYER_HEIGHT,
                FnStage::boxed("no-op:last", |_| {}),
            ),
        ]
    }
}

#[test]
fn an_inactive_plugin_set_produces_identical_gcode() {
    let mesh = fixture();
    let p = params();

    let baseline = deposited(&to_gcode(&process_mesh(&mesh, &p, &NullLogger), &p));
    let with_plugins = deposited(&to_gcode(
        &process_mesh_with_plugins(&mesh, &p, &NullLogger, &[]),
        &p,
    ));

    assert_same_deposition(
        &baseline,
        &with_plugins,
        "the plugin-aware entry point must not change the pipeline",
    );
}

#[test]
fn stages_that_do_nothing_change_nothing() {
    // A hook point that perturbs the pipeline merely by being occupied would
    // make every experiment a silent output change, and the QA baselines
    // meaningless as a gate.
    let mesh = fixture();
    let p = params();

    let plugins: Vec<Box<dyn Plugin>> = vec![Box::new(NoOp)];
    let baseline = deposited(&to_gcode(&process_mesh(&mesh, &p, &NullLogger), &p));
    let hooked = deposited(&to_gcode(
        &process_mesh_with_plugins(&mesh, &p, &NullLogger, &plugins),
        &p,
    ));

    assert_same_deposition(&baseline, &hooked, "occupying three hook points");
}

// ── The hooks actually fire ─────────────────────────────────────────────────

static RAN: AtomicUsize = AtomicUsize::new(0);

/// A plugin that both observes and edits, so a passing byte-identity test
/// above cannot be explained by the hooks never running.
struct Meddler;

impl Plugin for Meddler {
    fn manifest(&self) -> PluginManifest {
        PluginManifest::experiment("meddler", "Meddler", "Counts stages and drops every wall.")
    }
    fn stages(&self) -> Vec<StageRegistration> {
        vec![
            StageRegistration::after(
                ids::SLICING,
                FnStage::boxed("meddler:count", |cx: &mut SliceContext<'_>| {
                    RAN.fetch_add(cx.layers.len(), Ordering::SeqCst);
                }),
            ),
            StageRegistration::after(
                ids::WALL_GENERATION,
                FnStage::boxed("meddler:strip", |cx: &mut SliceContext<'_>| {
                    for layer in cx.layers.iter_mut() {
                        let keep: Vec<usize> = (0..layer.paths.len())
                            .filter(|i| layer.role_for_path(*i) != ExtrusionRole::InnerWall)
                            .collect();
                        let paths: Vec<_> = keep
                            .iter()
                            .map(|&i| layer.paths.iter().nth(i).unwrap().clone())
                            .collect();
                        let roles: Vec<_> = keep.iter().map(|&i| layer.role_for_path(i)).collect();
                        let widths: Vec<_> =
                            keep.iter().map(|&i| layer.width_for_path(i)).collect();
                        layer.paths = clipper2::Paths::new(paths);
                        layer.path_roles = roles;
                        layer.path_widths = widths;
                        layer.path_vertex_widths.clear();
                        layer.path_is_open.clear();
                    }
                }),
            ),
        ]
    }
}

#[test]
fn a_registered_stage_runs_and_its_edits_reach_the_output() {
    let mesh = fixture();
    let p = params();

    RAN.store(0, Ordering::SeqCst);
    let plugins: Vec<Box<dyn Plugin>> = vec![Box::new(Meddler)];
    let layers = process_mesh_with_plugins(&mesh, &p, &NullLogger, &plugins);

    assert!(
        RAN.load(Ordering::SeqCst) > 0,
        "the observing stage never ran, so the identity tests above prove nothing"
    );
    assert!(
        layers
            .iter()
            .all(|l| (0..l.paths.len()).all(|i| l.role_for_path(i) != ExtrusionRole::InnerWall)),
        "the editing stage's changes must survive to the finished layers"
    );
}

/// A wrapper that skips the stage it takes over.
struct SkipInfill {
    skipped: &'static AtomicUsize,
}

static SKIPPED: AtomicUsize = AtomicUsize::new(0);

impl StageWrapper for SkipInfill {
    fn id(&self) -> StageId {
        StageId::new("skip-infill")
    }
    fn run(&self, _cx: &mut SliceContext<'_>, _inner: &dyn Stage) {
        self.skipped.fetch_add(1, Ordering::SeqCst);
    }
}

struct NoInfill;

impl Plugin for NoInfill {
    fn manifest(&self) -> PluginManifest {
        PluginManifest::experiment("no-infill", "No infill", "Wraps the infill stage away.")
    }
    fn stages(&self) -> Vec<StageRegistration> {
        vec![StageRegistration::wrap(
            ids::INFILL,
            Box::new(SkipInfill { skipped: &SKIPPED }),
        )]
    }
}

#[test]
fn a_wrapper_can_replace_a_core_stage_outright() {
    // The family the debug-capture plugin uses to swap in the sequential wall
    // generator. If a wrapper could not suppress the stage it takes over,
    // that plugin would have to be a second pipeline again.
    let mesh = fixture();
    let p = params();

    SKIPPED.store(0, Ordering::SeqCst);
    let plugins: Vec<Box<dyn Plugin>> = vec![Box::new(NoInfill)];
    let layers = process_mesh_with_plugins(&mesh, &p, &NullLogger, &plugins);

    assert_eq!(
        SKIPPED.load(Ordering::SeqCst),
        1,
        "the wrapper must run once"
    );
    assert!(
        layers
            .iter()
            .all(|l| (0..l.paths.len()).all(|i| l.role_for_path(i) != ExtrusionRole::Infill)),
        "wrapping the infill stage away must leave no sparse infill"
    );
    assert!(
        layers
            .iter()
            .any(|l| (0..l.paths.len()).any(|i| l.role_for_path(i) == ExtrusionRole::OuterWall)),
        "…and must leave the rest of the pipeline alone"
    );
}

// ── The stage list is the hook surface ──────────────────────────────────────

#[test]
fn the_core_stage_order_is_what_plugins_target() {
    // Every id here is a public hook point: a plugin naming one is entitled to
    // run on that side of it. Changing this list is an API change, not an
    // implementation detail — hence a test that has to be edited deliberately.
    let ids: Vec<String> = core_stages()
        .ids()
        .iter()
        .map(|id| id.as_str().to_string())
        .collect();

    assert_eq!(
        ids,
        vec![
            ids::SLICING,
            ids::COMPENSATION,
            ids::ELEPHANT_FOOT,
            ids::WALL_GENERATION,
            ids::INFILL_REGION_SNAPSHOT,
            ids::WALL_RESTRICTIONS,
            ids::INTERIOR_REGIONS,
            ids::OVERHANG_SUPPORT_SNAPSHOT,
            ids::SURFACES,
            ids::OVERHANG_CLASSIFICATION,
            ids::GAP_FILL_PRUNE,
            ids::INFILL,
            ids::PATH_ORDERING,
            ids::FLOW_COMPENSATION,
            ids::FUZZY_SKIN,
            ids::BED_ADHESION,
            ids::FIRST_LAYER_HEIGHT,
        ]
    );
}

// ── The debug pipeline is the production one ────────────────────────────────

#[test]
fn the_debug_pipeline_returns_the_same_layers_as_production() {
    // It used to claim this in its doc comment and not deliver: the duplicated
    // copy had drifted and skipped path ordering and bed adhesion entirely, so
    // `--debug-geometry` wrote unordered G-code with no skirt.
    let mesh = fixture();
    let mut p = params();
    p.adhesion_type = slicer_engine::settings::params::AdhesionType::Skirt;

    let production = process_mesh(&mesh, &p, &NullLogger);
    let mut debug = slicer_engine::debug::DebugGeometry::new();
    let debugged = slicer_engine::core::process_mesh_debug(&mesh, &p, &NullLogger, &mut debug);

    assert_eq!(production.len(), debugged.len(), "layer counts must match");

    // Compared as the *sequence of role groups*, not as a path list. What went
    // wrong before was that whole stages were missing, and that is exactly what
    // a run-length-encoded role sequence shows: path ordering is what collects
    // a layer's paths into one contiguous run per role, and adhesion is what
    // puts a `Skirt` group in front of layer 0.
    //
    // Path *counts* are deliberately not compared. The debug run generates
    // walls sequentially, which the QA harness documents as emitting slightly
    // different medial beads than the parallel generator; that shifts the
    // infill boundary and can leave one extra sub-millimetre infill dash on a
    // layer. Real, known, and not what this test is about.
    let groups = |layer: &slicer_engine::core::SliceLayer| -> Vec<ExtrusionRole> {
        let mut out: Vec<ExtrusionRole> = Vec::new();
        for k in 0..layer.paths.len() {
            let role = layer.role_for_path(k);
            if role == ExtrusionRole::GapFill {
                continue;
            }
            if out.last() != Some(&role) {
                out.push(role);
            }
        }
        out
    };

    for (i, (a, b)) in production.iter().zip(debugged.iter()).enumerate() {
        assert_eq!(groups(a), groups(b), "layer {i}: role groups");
    }

    // The two stages the duplicated pipeline silently skipped. A skirt exists
    // only if bed adhesion ran; the role-group sequences matching above is what
    // shows path ordering did, since an unordered layer groups differently.
    assert!(
        groups(&debugged[0]).contains(&ExtrusionRole::Skirt),
        "the debug run must print the skirt the duplicated pipeline used to drop"
    );
    assert!(
        !debug.records.is_empty(),
        "snapshots must still be captured"
    );
}
