; HEADER_BLOCK_START
; generated by Cold Crabby development on 2026-08-25 at 17:00:02
; flavor: Marlin
; model: simple-cube
; total layers count = 5
; max_z_height = 0.90 mm
; filament used [mm] = 0.37
; filament used [cm3] = 0.00
; filament used [g] = 0.00
; estimated printing time = 0s
; model bounding box [mm] = 0.20,0.20,0.10 -> 0.80,0.80,0.90
; HEADER_BLOCK_END
; layer_height: 0.2 mm
; nozzle_temp: 210 °C
; bed_temp: 60 °C
; print_speed: 60 mm/s | perimeter: 45 | infill: 70 | bridge: 25 | first_layer: 25
; wall_count: 3 walls (arachne generator)
; infill_density: 20%
; ---
G21 ; millimetres
G90 ; absolute positioning
M82 ; extruder absolute mode
M104 S210 ; set nozzle temperature
M140 S60 ; set bed temperature
G28 ; home all axes
M109 S210 ; wait for nozzle temperature
M190 S60 ; wait for bed temperature
G92 E0 ; reset extruder
M82 ; extruder absolute mode
G92 E0
;LAYER_CHANGE
;Z:0.100
;HEIGHT:0.200
;LAYER_TIME:0.0
;BEFORE_LAYER_CHANGE
;0.100
G92 E0
G1 Z0.100 F9000
;AFTER_LAYER_CHANGE
;0.100
M106 S255
;TYPE:Outer wall
;WIDTH:0.40mm
G1 E-1.00000 F3000 ; retract
G1 Z0.300 F9000 ; z-hop
G1 X0.800 Y0.200 F9000 ; travel
G1 Z0.100 F9000 ; lower
G1 E0.00000 F3000 ; un-retract
G1 X0.800 Y0.800 E0.01996 F1500
G1 X0.200 Y0.800 E0.03991 F1500
G1 X0.200 Y0.200 E0.05987 F1500
G1 X0.600 Y0.200 E0.07317 F1500
G1 X0.800 Y0.200 F1500 ; coasting close
;LAYER_CHANGE
;Z:0.300
;HEIGHT:0.200
;LAYER_TIME:0.0
;BEFORE_LAYER_CHANGE
;0.300
G92 E0
G1 Z0.300 F9000
;AFTER_LAYER_CHANGE
;0.300
M106 S255
;TYPE:Outer wall
;WIDTH:0.40mm
G1 E-1.00000 F3000 ; retract
G1 Z0.500 F9000 ; z-hop
G1 X0.800 Y0.200 F9000 ; travel
G1 Z0.300 F9000 ; lower
G1 E0.00000 F3000 ; un-retract
G1 X0.800 Y0.800 E0.01996 F2700
G1 X0.200 Y0.800 E0.03991 F2700
G1 X0.200 Y0.200 E0.05987 F2700
G1 X0.600 Y0.200 E0.07317 F2700
G1 X0.800 Y0.200 F2700 ; coasting close
;LAYER_CHANGE
;Z:0.500
;HEIGHT:0.200
;LAYER_TIME:0.0
;BEFORE_LAYER_CHANGE
;0.500
G92 E0
G1 Z0.500 F9000
;AFTER_LAYER_CHANGE
;0.500
M106 S255
;TYPE:Outer wall
;WIDTH:0.40mm
G1 E-1.00000 F3000 ; retract
G1 Z0.700 F9000 ; z-hop
G1 X0.800 Y0.200 F9000 ; travel
G1 Z0.500 F9000 ; lower
G1 E0.00000 F3000 ; un-retract
G1 X0.800 Y0.800 E0.01996 F2700
G1 X0.200 Y0.800 E0.03991 F2700
G1 X0.200 Y0.200 E0.05987 F2700
G1 X0.600 Y0.200 E0.07317 F2700
G1 X0.800 Y0.200 F2700 ; coasting close
;LAYER_CHANGE
;Z:0.700
;HEIGHT:0.200
;LAYER_TIME:0.0
;BEFORE_LAYER_CHANGE
;0.700
G92 E0
G1 Z0.700 F9000
;AFTER_LAYER_CHANGE
;0.700
M106 S255
;TYPE:Outer wall
;WIDTH:0.40mm
G1 E-1.00000 F3000 ; retract
G1 Z0.900 F9000 ; z-hop
G1 X0.800 Y0.200 F9000 ; travel
G1 Z0.700 F9000 ; lower
G1 E0.00000 F3000 ; un-retract
G1 X0.800 Y0.800 E0.01996 F2700
G1 X0.200 Y0.800 E0.03991 F2700
G1 X0.200 Y0.200 E0.05987 F2700
G1 X0.600 Y0.200 E0.07317 F2700
G1 X0.800 Y0.200 F2700 ; coasting close
;LAYER_CHANGE
;Z:0.900
;HEIGHT:0.200
;LAYER_TIME:0.0
;BEFORE_LAYER_CHANGE
;0.900
G92 E0
G1 Z0.900 F9000
;AFTER_LAYER_CHANGE
;0.900
M106 S255
;TYPE:Outer wall
;WIDTH:0.40mm
G1 E-1.00000 F3000 ; retract
G1 Z1.100 F9000 ; z-hop
G1 X0.800 Y0.200 F9000 ; travel
G1 Z0.900 F9000 ; lower
G1 E0.00000 F3000 ; un-retract
G1 X0.800 Y0.800 E0.01996 F2700
G1 X0.200 Y0.800 E0.03991 F2700
G1 X0.200 Y0.200 E0.05987 F2700
G1 X0.600 Y0.200 E0.07317 F2700
G1 X0.800 Y0.200 F2700 ; coasting close
; end of print
G91 ; relative positioning
G1 E-2 F3000 ; final retract
G1 Z5 F3000 ; lift nozzle
G90 ; absolute positioning
G28 X0 Y0 ; park
M104 S0 ; nozzle off
M140 S0 ; bed off
M84 ; disable motors
